<a href="https://colab.research.google.com/github/QnAline/Projects/blob/main/East%26South.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading the dataset

In [1]:
import pandas as pd
df_2023= pd.read_excel("RI_east&southern_2023.xlsx")
df_2024= pd.read_excel("RI_east&southern_2024.xlsx")
print("Data for 2023 East & South vaccination:")
df_2023

Data for 2023 East & South vaccination:

,Month,Year,District_Name,DateFirstEntered,DateLastUpdate,DateReceivedatNat,TotalNumHF,NumHFReportsIncluded,NumHFReportsTimely,BCG_GE1,...,RTSS3_GE1,RTSS3_GE1_Out,RTSS4_L1,RTSS4_L1_Out,RTSS4_GE1,RTSS4_GE1_Out,MenA,IPV2_L1,IPV2_Out,TCV1_L1
0,1,2023,Fomboni,NaT,NaT,NaT,NaN,NaN,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
1,2,2023,Fomboni,NaT,NaT,NaT,NaN,NaN,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
2,3,2023,Fomboni,NaT,NaT,NaT,NaN,NaN,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
3,1,2023,Mrémani,NaT,NaT,NaT,NaN,NaN,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
4,2,2023,Mrémani,NaT,NaT,NaT,NaN,NaN,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15809,9,2023,Busega DC,NaT,NaT,NaT,32.0,31.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
15810,1,2023,Busokelo DC,NaT,NaT,NaT,29.0,25.0,23.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
15811,10,2023,Busokelo DC,NaT,NaT,NaT,29.0,25.0,13.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
15812,11,2023,Busokelo DC,NaT,NaT,NaT,29.0,25.0,25.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
15813,12,2023,Busokelo DC,NaT,NaT,NaT,29.0,25.0,25.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0

In [2]:
print("Data for 2024 East & South vaccination:")
df_2024

Data for 2024 East & South vaccination:

,Month,Year,District_Name,DateFirstEntered,DateLastUpdate,DateReceivedatNat,TotalNumHF,NumHFReportsIncluded,NumHFReportsTimely,BCG_GE1,...,RTSS3_GE1,RTSS3_GE1_Out,RTSS4_L1,RTSS4_L1_Out,RTSS4_GE1,RTSS4_GE1_Out,MenA,IPV2_L1,IPV2_Out,TCV1_L1
0,1,2024,Mtama DC,NaT,NaT,NaT,42.0,41.0,38.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
1,1,2024,Nachingwea dc,NaT,NaT,NaT,52.0,43.0,43.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
2,1,2024,Ruangwa dc,NaT,NaT,NaT,44.0,40.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0
3,1,2024,Chibombo,NaT,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,188.0,0,0
4,1,2024,Chisamba,NaT,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,159.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3429,2,2024,Zombo,NaT,NaT,NaT,23.0,23.0,18.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,350.0,0,0
3430,3,2024,Zombo,NaT,NaT,NaT,23.0,23.0,21.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,538.0,0,0
3431,4,2024,Zombo,NaT,NaT,NaT,23.0,23.0,22.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,486.0,0,0
3432,3,2024,Mberengwa,NaT,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,593.0,0,131
3433,3,2024,Shurugwi,NaT,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,299.0,0,5

# Data cleaning

## Missing values

# 2023

In [3]:
print(df_2023.isnull().sum())

Month                   0
Year                    0
District_Name           0
DateFirstEntered    15346
DateLastUpdate      15526
                    ...
RTSS4_GE1_Out       15478
MenA                    0
IPV2_L1               180
IPV2_Out                0
TCV1_L1                 0
Length: 148, dtype: int64

In [4]:
threshold = 0.5 # drop columns with more than 50% missing values
df_2023.dropna(axis=1, thresh=int(threshold * len(df_2023)), inplace=True)
print(df_2023.isnull().sum())

Month                 0
Year                  0
District_Name         0
OPVBirth           3589
OPV1_GE1           6872
OPV2_L1            2036
OPV2_GE1           6879
Measles_GE1        6686
COMP_L1            6939
DHH3_GE1_Static    6797
DHH2_GE1_Static    6856
DHH_GE1_Static     6861
DHH2_L1_Static     2375
Pneumo2_L1         2558
Country_Code          0
Province_Name         0
DHH3_L1_Static        8
DHH_L1_Static         4
Measles_L1            4
OPV1_L1              21
IPV1_L1             235
OPV3_L1             629
BCG_L1                2
Pneumo1_L1         1149
Pneumo3_L1         2540
Rota1_L1           1189
Rota2_L1           1146
Measles2_GE1       1154
TT1_PW             4549
TT2_PW             4116
TT3_PW             7285
TT4_PW             7300
TT5_PW             7329
TT1_CBA            5527
TT2_CBA            5527
TT3_CBA            7782
TT5_CBA            7810
MenA                  0
IPV2_L1             180
IPV2_Out              0
TCV1_L1               0
dtype: int64

In [5]:
df_2023.fillna(method='bfill', inplace=True)
print(df_2023.isnull().sum())

Month               0
Year                0
District_Name       0
OPVBirth            0
OPV1_GE1            0
OPV2_L1             0
OPV2_GE1            0
Measles_GE1         0
COMP_L1            14
DHH3_GE1_Static     0
DHH2_GE1_Static     0
DHH_GE1_Static      0
DHH2_L1_Static      0
Pneumo2_L1          0
Country_Code        0
Province_Name       0
DHH3_L1_Static      0
DHH_L1_Static       0
Measles_L1          0
OPV1_L1             0
IPV1_L1             0
OPV3_L1             0
BCG_L1              0
Pneumo1_L1          0
Pneumo3_L1          0
Rota1_L1            0
Rota2_L1            0
Measles2_GE1        0
TT1_PW              0
TT2_PW              0
TT3_PW              0
TT4_PW              0
TT5_PW              0
TT1_CBA             0
TT2_CBA             0
TT3_CBA             0
TT5_CBA             0
MenA                0
IPV2_L1             0
IPV2_Out            0
TCV1_L1             0
dtype: int64

<ipython-input-5-9195b4e2ebea>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2023.fillna(method='bfill', inplace=True)

In [6]:
# Fill missing values with the median
median_value = df_2023['COMP_L1'].median()
df_2023['COMP_L1'].fillna(median_value, inplace=True)
print(df_2023.isnull().sum())

Month              0
Year               0
District_Name      0
OPVBirth           0
OPV1_GE1           0
OPV2_L1            0
OPV2_GE1           0
Measles_GE1        0
COMP_L1            0
DHH3_GE1_Static    0
DHH2_GE1_Static    0
DHH_GE1_Static     0
DHH2_L1_Static     0
Pneumo2_L1         0
Country_Code       0
Province_Name      0
DHH3_L1_Static     0
DHH_L1_Static      0
Measles_L1         0
OPV1_L1            0
IPV1_L1            0
OPV3_L1            0
BCG_L1             0
Pneumo1_L1         0
Pneumo3_L1         0
Rota1_L1           0
Rota2_L1           0
Measles2_GE1       0
TT1_PW             0
TT2_PW             0
TT3_PW             0
TT4_PW             0
TT5_PW             0
TT1_CBA            0
TT2_CBA            0
TT3_CBA            0
TT5_CBA            0
MenA               0
IPV2_L1            0
IPV2_Out           0
TCV1_L1            0
dtype: int64

# 2024

In [7]:
print(df_2024.isnull().sum())

Month                  0
Year                   0
District_Name          0
DateFirstEntered    3344
DateLastUpdate      3396
                    ...
RTSS4_GE1_Out       3434
MenA                   0
IPV2_L1              383
IPV2_Out               0
TCV1_L1                0
Length: 148, dtype: int64

In [8]:
threshold = 0.5 # drop columns with more than 50% missing values
df_2024.dropna(axis=1, thresh=int(threshold * len(df_2024)), inplace=True)
print(df_2024.isnull().sum())

Month                0
Year                 0
District_Name        0
OPVBirth           963
OPV2_L1            678
DHH2_L1_Static     694
Pneumo2_L1         576
Country_Code         0
Province_Name        0
DHH3_L1_Static     139
DHH_L1_Static      139
Measles_L1         575
OPV1_L1             19
IPV1_L1            235
OPV3_L1            124
BCG_L1              23
Pneumo1_L1          21
Pneumo3_L1         576
Rota1_L1            22
Rota2_L1           578
Measles2_GE1       113
TT1_PW            1555
TT2_PW            1326
MenA                 0
IPV2_L1            383
IPV2_Out             0
TCV1_L1              0
dtype: int64

In [9]:
df_2024.fillna(method='bfill', inplace=True)
print(df_2024.isnull().sum())

Month             0
Year              0
District_Name     0
OPVBirth          2
OPV2_L1           0
DHH2_L1_Static    0
Pneumo2_L1        0
Country_Code      0
Province_Name     0
DHH3_L1_Static    0
DHH_L1_Static     0
Measles_L1        0
OPV1_L1           0
IPV1_L1           0
OPV3_L1           0
BCG_L1            0
Pneumo1_L1        0
Pneumo3_L1        0
Rota1_L1          0
Rota2_L1          0
Measles2_GE1      0
TT1_PW            2
TT2_PW            0
MenA              0
IPV2_L1           0
IPV2_Out          0
TCV1_L1           0
dtype: int64

<ipython-input-9-912ba6f1e0f1>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2024.fillna(method='bfill', inplace=True)

In [10]:
# Fill missing values with the median
median_value = df_2024['OPVBirth'].median()
df_2024['OPVBirth'].fillna(median_value, inplace=True)
median_value = df_2024['TT1_PW'].median()
df_2024['TT1_PW'].fillna(median_value, inplace=True)
print(df_2024.isnull().sum())

Month             0
Year              0
District_Name     0
OPVBirth          0
OPV2_L1           0
DHH2_L1_Static    0
Pneumo2_L1        0
Country_Code      0
Province_Name     0
DHH3_L1_Static    0
DHH_L1_Static     0
Measles_L1        0
OPV1_L1           0
IPV1_L1           0
OPV3_L1           0
BCG_L1            0
Pneumo1_L1        0
Pneumo3_L1        0
Rota1_L1          0
Rota2_L1          0
Measles2_GE1      0
TT1_PW            0
TT2_PW            0
MenA              0
IPV2_L1           0
IPV2_Out          0
TCV1_L1           0
dtype: int64

# Datatypes

In [11]:
print(df_2023.dtypes)

Month                int64
Year                 int64
District_Name       object
OPVBirth           float64
OPV1_GE1           float64
OPV2_L1            float64
OPV2_GE1           float64
Measles_GE1        float64
COMP_L1            float64
DHH3_GE1_Static    float64
DHH2_GE1_Static    float64
DHH_GE1_Static     float64
DHH2_L1_Static     float64
Pneumo2_L1         float64
Country_Code        object
Province_Name       object
DHH3_L1_Static     float64
DHH_L1_Static      float64
Measles_L1         float64
OPV1_L1            float64
IPV1_L1            float64
OPV3_L1            float64
BCG_L1             float64
Pneumo1_L1         float64
Pneumo3_L1         float64
Rota1_L1           float64
Rota2_L1           float64
Measles2_GE1       float64
TT1_PW             float64
TT2_PW             float64
TT3_PW             float64
TT4_PW             float64
TT5_PW             float64
TT1_CBA            float64
TT2_CBA            float64
TT3_CBA            float64
TT5_CBA            float64
MenA                 int64
IPV2_L1            float64
IPV2_Out             int64
TCV1_L1              int64
dtype: object

In [12]:
print(df_2024.dtypes)

Month               int64
Year                int64
District_Name      object
OPVBirth          float64
OPV2_L1           float64
DHH2_L1_Static    float64
Pneumo2_L1        float64
Country_Code       object
Province_Name      object
DHH3_L1_Static    float64
DHH_L1_Static     float64
Measles_L1        float64
OPV1_L1           float64
IPV1_L1           float64
OPV3_L1           float64
BCG_L1            float64
Pneumo1_L1        float64
Pneumo3_L1        float64
Rota1_L1          float64
Rota2_L1          float64
Measles2_GE1      float64
TT1_PW            float64
TT2_PW            float64
MenA                int64
IPV2_L1           float64
IPV2_Out            int64
TCV1_L1             int64
dtype: object

# Removing Duplicates rows

In [13]:
df_2023.drop_duplicates(inplace=True)
df_2024.drop_duplicates(inplace=True)

# Data normalization

2023

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
numerical_cols = [
    'OPVBirth', 'OPV1_GE1', 'OPV2_L1', 'OPV2_GE1', 'Measles_GE1',
    'COMP_L1', 'DHH3_GE1_Static', 'DHH2_GE1_Static', 'DHH_GE1_Static',
    'DHH2_L1_Static', 'Pneumo2_L1', 'Measles_L1', 'OPV1_L1', 'IPV1_L1',
    'OPV3_L1', 'BCG_L1', 'Pneumo1_L1', 'Pneumo3_L1', 'Rota1_L1',
    'Rota2_L1', 'Measles2_GE1', 'TT1_PW', 'TT2_PW', 'TT3_PW', 'TT4_PW',
    'TT5_PW', 'TT1_CBA', 'TT2_CBA', 'TT3_CBA', 'TT5_CBA', 'IPV2_L1'
]
df_2023[numerical_cols] = scaler.fit_transform(df_2023[numerical_cols])
df_2023

,Month,Year,District_Name,OPVBirth,OPV1_GE1,OPV2_L1,OPV2_GE1,Measles_GE1,COMP_L1,DHH3_GE1_Static,...,TT4_PW,TT5_PW,TT1_CBA,TT2_CBA,TT3_CBA,TT5_CBA,MenA,IPV2_L1,IPV2_Out,TCV1_L1
0,1,2023,Fomboni,0.007476,0.0,0.004171,0.0,0.000000,0.000000,0.0,...,0.000145,0.000341,0.000054,0.000152,0.000578,0.001010,0,0.0,0,0
1,2,2023,Fomboni,0.006531,0.0,0.004505,0.0,0.000447,0.000000,0.0,...,0.000436,0.000273,0.000000,0.000000,0.000868,0.000505,0,0.0,0,0
2,3,2023,Fomboni,0.007397,0.0,0.005422,0.0,0.000746,0.000000,0.0,...,0.000109,0.000205,0.000054,0.000000,0.001735,0.002525,0,0.0,0,0
3,1,2023,Mrémani,0.004879,0.0,0.001752,0.0,0.000000,0.000000,0.0,...,0.000073,0.000273,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0
4,2,2023,Mrémani,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000036,0.000409,0.000269,0.000101,0.000578,0.000000,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15809,9,2023,Busega DC,0.130941,0.0,0.135302,0.0,0.000000,0.002259,0.0,...,0.010762,0.020250,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0
15810,1,2023,Busokelo DC,0.039345,0.0,0.030531,0.0,0.000000,0.002259,0.0,...,0.002436,0.004091,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0
15811,10,2023,Busokelo DC,0.036276,0.0,0.027110,0.0,0.000000,0.002259,0.0,...,0.001345,0.002523,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0
15812,11,2023,Busokelo DC,0.030453,0.0,0.024775,0.0,0.000000,0.002259,0.0,...,0.001454,0.002114,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0
15813,12,2023,Busokelo DC,0.029509,0.0,0.027277,0.0,0.000000,0.002259,0.0,...,0.001709,0.003068,0.000000,0.000000,0.000000,0.000000,0,0.0,0,0

2024

In [15]:
numerical_cols = [
    'OPVBirth', 'OPV2_L1', 'DHH2_L1_Static', 'Pneumo2_L1',
    'DHH3_L1_Static', 'DHH_L1_Static', 'Measles_L1', 'OPV1_L1',
    'IPV1_L1', 'OPV3_L1', 'BCG_L1', 'Pneumo1_L1', 'Pneumo3_L1',
    'Rota1_L1', 'Rota2_L1', 'Measles2_GE1', 'TT1_PW', 'TT2_PW',
    'IPV2_L1', 'IPV2_Out', 'TCV1_L1'
]
df_2024[numerical_cols] = scaler.fit_transform(df_2024[numerical_cols])
df_2024

,Month,Year,District_Name,OPVBirth,OPV2_L1,DHH2_L1_Static,Pneumo2_L1,Country_Code,Province_Name,DHH3_L1_Static,...,Pneumo3_L1,Rota1_L1,Rota2_L1,Measles2_GE1,TT1_PW,TT2_PW,MenA,IPV2_L1,IPV2_Out,TCV1_L1
0,1,2024,Mtama DC,0.052308,0.035022,0.021052,0.034980,TAN,Lindi,0.030046,...,0.042576,0.023552,0.024739,0.031437,0.000000,0.000000,0,0.000000,0.0,0.000000
1,1,2024,Nachingwea dc,0.050932,0.000000,0.000000,0.000000,TAN,Lindi,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.0,0.000000
2,1,2024,Ruangwa dc,0.035578,0.000000,0.000000,0.000000,TAN,Lindi,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.0,0.000000
3,1,2024,Chibombo,0.059720,0.098149,0.044703,0.101054,ZAM,Central,0.048279,...,0.093341,0.067398,0.065244,0.069611,0.000000,0.000000,0,0.032291,0.0,0.000000
4,1,2024,Chisamba,0.027848,0.031218,0.021000,0.033771,ZAM,Central,0.024974,...,0.034753,0.019894,0.021586,0.025168,0.000000,0.000000,0,0.027310,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3429,2,2024,Zombo,0.077510,0.092874,0.055723,0.095008,UGA,West Nile,0.068695,...,0.099982,0.059338,0.067123,0.030314,0.079939,0.029868,0,0.060117,0.0,0.000000
3430,3,2024,Zombo,0.074651,0.082324,0.049174,0.082225,UGA,West Nile,0.065164,...,0.093705,0.048820,0.057725,0.026104,0.105337,0.043459,0,0.092408,0.0,0.000000
3431,4,2024,Zombo,0.087569,0.075320,0.049589,0.079461,UGA,West Nile,0.070300,...,0.100073,0.054822,0.055118,0.089072,0.092931,0.033590,0,0.083476,0.0,0.000000
3432,3,2024,Mberengwa,0.047967,0.051712,0.031916,0.053550,ZIM,Midlands,0.045390,...,0.064410,0.038701,0.037958,0.065307,0.067884,0.056186,0,0.101855,0.0,0.032266
3433,3,2024,Shurugwi,0.047967,0.021792,0.013723,0.023147,ZIM,Midlands,0.017463,...,0.024836,0.015606,0.015583,0.025543,0.067884,0.026145,0,0.051357,0.0,0.001232

# Latitude and Longitude

In [16]:
from geopy.geocoders import ArcGIS
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import pandas as pd
from tqdm import tqdm
import time

geolocator = ArcGIS()

def get_coordinates(district_name, max_retries=3):
    for attempt in range(max_retries):
        try:
            location = geolocator.geocode(district_name, exactly_one=True)
            if location:
                return location.latitude, location.longitude
            return None, None
        except (GeocoderTimedOut, GeocoderServiceError) as e:
            if attempt == max_retries - 1:
                print(f"Error fetching coordinates for {district_name}: {e}")
                return None, None
            time.sleep(1)

unique_districts = df_2023['District_Name'].unique()

coordinates = {}
for district in tqdm(unique_districts, desc="Fetching coordinates"):
    lat, lon = get_coordinates(district)
    coordinates[district] = (lat, lon)
    time.sleep(1)

coord_df = pd.DataFrame.from_dict(coordinates, orient='index', columns=['Latitude', 'Longitude'])
coord_df.index.name = 'District_Name'
coord_df = coord_df.reset_index()

result_df = df_2023.merge(coord_df, on='District_Name', how='left')

result_df = result_df.loc[:, ~result_df.columns.duplicated()]
result_df.to_excel('Lat_long_df_2023.xlsx', index=False)

print(result_df.head())

Fetching coordinates: 100%|██████████| 1334/1334 [23:37<00:00,  1.06s/it]

   Month  Year District_Name  OPVBirth  OPV1_GE1   OPV2_L1  OPV2_GE1  \
0      1  2023       Fomboni  0.007476       0.0  0.004171       0.0
1      2  2023       Fomboni  0.006531       0.0  0.004505       0.0
2      3  2023       Fomboni  0.007397       0.0  0.005422       0.0
3      1  2023       Mrémani  0.004879       0.0  0.001752       0.0
4      2  2023       Mrémani  0.000000       0.0  0.000000       0.0

   Measles_GE1  COMP_L1  DHH3_GE1_Static  ...   TT1_CBA   TT2_CBA   TT3_CBA  \
0     0.000000      0.0              0.0  ...  0.000054  0.000152  0.000578
1     0.000447      0.0              0.0  ...  0.000000  0.000000  0.000868
2     0.000746      0.0              0.0  ...  0.000054  0.000000  0.001735
3     0.000000      0.0              0.0  ...  0.000000  0.000000  0.000000
4     0.000000      0.0              0.0  ...  0.000269  0.000101  0.000578

    TT5_CBA MenA IPV2_L1  IPV2_Out  TCV1_L1  Latitude  Longitude
0  0.001010    0     0.0         0        0 -12.28396  43.743736
1  0.000505    0     0.0         0        0 -12.28396  43.743736
2  0.002525    0     0.0         0        0 -12.28396  43.743736
3  0.000000    0     0.0         0        0 -12.31095  44.497549
4  0.000000    0     0.0         0        0 -12.31095  44.497549

[5 rows x 43 columns]

In [17]:
from geopy.geocoders import ArcGIS
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import pandas as pd
from tqdm import tqdm
import time

geolocator = ArcGIS()

def get_coordinates(district_name, max_retries=3):
    for attempt in range(max_retries):
        try:
            location = geolocator.geocode(district_name, exactly_one=True)
            if location:
                return location.latitude, location.longitude
            return None, None
        except (GeocoderTimedOut, GeocoderServiceError) as e:
            if attempt == max_retries - 1:
                print(f"Error fetching coordinates for {district_name}: {e}")
                return None, None
            time.sleep(1)

unique_districts = df_2024['District_Name'].unique()

coordinates = {}
for district in tqdm(unique_districts, desc="Fetching coordinates"):
    lat, lon = get_coordinates(district)
    coordinates[district] = (lat, lon)
    time.sleep(0.5)

coord_df = pd.DataFrame.from_dict(coordinates, orient='index', columns=['Latitude', 'Longitude'])
coord_df.index.name = 'District_Name'
coord_df = coord_df.reset_index()

result_df = df_2024.merge(coord_df, on='District_Name', how='left')

result_df = result_df.loc[:, ~result_df.columns.duplicated()]
result_df.to_excel('Lat_long_df_2024.xlsx', index=False)
print(result_df.head())

Fetching coordinates: 100%|██████████| 1086/1086 [12:05<00:00,  1.50it/s]

   Month  Year  District_Name  OPVBirth   OPV2_L1  DHH2_L1_Static  Pneumo2_L1  \
0      1  2024       Mtama DC  0.052308  0.035022        0.021052    0.034980
1      1  2024  Nachingwea dc  0.050932  0.000000        0.000000    0.000000
2      1  2024     Ruangwa dc  0.035578  0.000000        0.000000    0.000000
3      1  2024       Chibombo  0.059720  0.098149        0.044703    0.101054
4      1  2024       Chisamba  0.027848  0.031218        0.021000    0.033771

  Country_Code Province_Name  DHH3_L1_Static  ...  Rota2_L1  Measles2_GE1  \
0          TAN         Lindi        0.030046  ...  0.024739      0.031437
1          TAN         Lindi        0.000000  ...  0.000000      0.000000
2          TAN         Lindi        0.000000  ...  0.000000      0.000000
3          ZAM       Central        0.048279  ...  0.065244      0.069611
4          ZAM       Central        0.024974  ...  0.021586      0.025168

   TT1_PW  TT2_PW  MenA   IPV2_L1  IPV2_Out  TCV1_L1   Latitude  Longitude
0     0.0     0.0     0  0.000000       0.0      0.0  33.490370  -5.561150
1     0.0     0.0     0  0.000000       0.0      0.0 -10.402739  38.367583
2     0.0     0.0     0  0.000000       0.0      0.0 -10.090322  38.982749
3     0.0     0.0     0  0.032291       0.0      0.0 -14.803351  28.057642
4     0.0     0.0     0  0.027310       0.0      0.0 -14.978852  28.376546

[5 rows x 29 columns]